"""
Report generation utilities
"""

import datetime
from config import THRESHOLD, COMPANY_NAME

def generate_inspection_report(customer_id, result_series, data_series):
    """Generate detailed inspection report text"""
    report_content = f"""
# 🚨 ELECTRICITY THEFT INSPECTION REPORT 🚨
---
## 1. General Details
**Report Generation Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Customer ID (CONS_NO):** {customer_id}
**Prediction Model:** XGBoost Classifier
**Threshold Used:** {THRESHOLD*100}%
---

## 2. Prediction Summary
| Metric | Value |
| :--- | :--- |
| **Prediction Result** | **{result_series['Prediction']}** |
| **Theft Probability** | **{result_series['Theft_Probability']}** |
| **Risk Level** | **{result_series['Risk_Level']}** |
| **Action Recommended** | **{result_series['Next_Action']}** |
---

## 3. Explanatory Insights
**Theft Description:** {result_series['Theft_Description']}
---

## 4. Key Anomalous Features
| Feature | Value |
| :--- | :--- |
| **Zero Consumption Days** | {data_series.get('zero_consumption_days', 'N/A')} |
| **Std Dev of Consumption** | {data_series.get('std_consumption', 'N/A')} |
| **Max to Mean Ratio** | {data_series.get('max_to_mean_ratio', 'N/A')} |
| **Avg Consumption** | {data_series.get('avg_consumption', 'N/A')} |
---

## 5. Inspection Team Instructions
1. Conduct immediate on-site inspection of the premises.
2. Check meter physical condition and wiring integrity.
3. Take legal action if theft is confirmed.
**Report Generated By:** Automated ML System.
"""
    return report_content

