[theme]
primaryColor = "#7C3AED"
backgroundColor = "#F4F1FA"
secondaryBackgroundColor = "#EFEBF5"
textColor = "#332F3A"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false
